# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 14:07
from __future__ import unicode_literals

from django.db import migrations


def create_http_methods(apps, schema_editor):
    HTTPMethod = apps.get_model("management", "HTTPMethod")
    for name in 'GET', 'POST', 'PUT', 'DELETE':
        method = HTTPMethod(name=name)
        method.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_http_methods)
    ]